# Generated by Django 2.2.6 on 2019-12-19 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('temp_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=50)),
                ('theme_type', models.CharField(choices=[('ST', 'Sub_theme'), ('MT', 'Main_theme')], default=('ST', 'Sub_theme'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomm_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
                ('recomm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=(5, '5'))),
                ('rating_direct', models.BooleanField(default=False)),
                ('rating_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating_grade_expect', models.FloatField(blank=True, default=None, null=True)),
                ('rating_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Post')),
                ('rating_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='prating',
            field=models.ManyToManyField(default=None, through='news.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Theme'),
        ),
    ]
